---
title: "Procesamiento de datos con tidyverse"
---

# **Parte 2**

---------------------------------------------------------------------------------
## **Retomando la Parte 1**

```{r}
data_v14 <- read.csv("data_exp_11854-v14_task-5ksx.csv")
data_v15 <- read.csv("data_exp_11854-v15_task-5ksx.csv")
library(tidyverse)
data_raw <- bind_rows(data_v14, data_v15) %>% 
  rename("id" = Participant.Public.ID, "group" = randomiser.qg34, "RT" = Reaction.Time, "Acc" = Correct, "relation" = primeType, "familiarity" = trialType, "block" = 	block_testingSR) %>% 
  filter (Screen.Name == "target", display == "Tarea") %>% 
  select (id, group, relation, familiarity, block, prime, target, Response, Acc, RT) %>% 
  arrange (group, id, familiarity, block, target) %>% 
  mutate (accRT = ifelse(Acc == 1, RT, NA))
```


## **Participantes outliers por accuracy**
```{r}
data_outliers <- data_raw %>%
  filter (familiarity == "familiar") %>% 
  group_by(id, group) %>% 
  summarise(meanAcc = mean(Acc)) %>% 
  filter(meanAcc < 0.9)

#Los elimino de mi base de datos
data <- data_raw %>% 
  filter(!(id %in% data_outliers$id) & !(RT < 200))
```

  

## **Análisis exploratorio**

```{r}
data_condition <- data %>% 
  group_by(group, familiarity, relation) %>% 
  summarise(meanAcc = mean(Acc), 
            meanRT = mean(RT, na.rm = TRUE),
            sd_RT = sd(RT))
```


Guardar cuestionario
```{r}
library(xlsx)
write.xlsx(data, file= "PRIMINGdata.gorilla.xlsx")
```

## **Bonus track: cambio de tipo de base de datos**
Cambio el tipo de base de datos (de larga a ancha) con pivot_wider 

```{r}
data_wide <- data %>% 
  select(id, Acc, target, prime, relation) %>% 
  pivot_wider(names_from = id, values_from = Acc)
```

Vuelvo a la forma anterior con pivot_longer

```{r}
data_long <- data_wide %>% 
  pivot_longer(cols = c(-target, -prime, -relation), names_to = "id", values_to = "Acc")
```


